settings:
  cooldown-ms: 750
  use-jump-to-go-up: true
  use-sneak-to-go-down: true

elevators:
  default:
    material: DAYLIGHT_DETECTOR
    search-range: 16
    custom-block-ids: []
  fast:
    material: LIGHT_WEIGHTED_PRESSURE_PLATE
    search-range: 32
    custom-block-ids: []
