name: SopElevators
version: ${project.version}
main: net.enelson.sopelevators.SopElevatorsPlugin
api-version: '1.21'
author: E_NeLsOn
softdepend: [ACustomBlocks]
description: Elevator plugin with optional ACustomBlocks support.
commands:
  sopelevators:
    description: Main command for SopElevators.
    usage: /<command> reload
    permission: sopelevators.admin
permissions:
  sopelevators.admin:
    description: Allows reloading SopElevators configuration.
    default: op
