name: SopElevators
version: ${project.version}
main: net.enelson.sopelevators.SopElevatorsPlugin
api-version: '1.16'
author: E_NeLsOn
softdepend: [SopCustomBlocks]
description: Elevator plugin with optional SopCustomBlocks support.
commands:
  sopelevators:
    description: Main command for SopElevators.
    usage: /<command> reload
    permission: sopelevators.admin
permissions:
  sopelevators.admin:
    description: Allows reloading SopElevators configuration.
    default: op
